### PR TITLE
WYSIWYG config, added modules for functionality

### PR DESCRIPTION
**Pull request by Stacey1979**
Added the ckeditor_a11ychecker, ckeditor_balloonpanel, embed, and entity_embed modules. Added a library folder and added libraries for each ckeditor module.

### CODE REVIEW

**Comment by mariacha** [comment]
Visual regression test passed! 

View the [visual regression test report](https://circleci.com/gh/thinkshout/ucpe/228/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by mariacha** [comment]
Looking good to me -- VR tests and all passing. Did you enable and configure the modules on your local though? Do you have any outstanding changes in your `/config` folder?

**Comment by Stacey1979** [comment]
I did enable the modules on local and I configured the accessibility checker by adding it to the ckeditor toolbar. I originally added the Entity Embed to the toolbar as well, but since you suggested adding the related program as a paragraph, I removed it and didn't do much else with it.

**Comment by mariacha** [comment]
Hmmm. There's definitely config missing there. Will you do a `lando drush cex` and see if anything else comes in?

**Comment by mariacha** [comment]
Visual regression test passed! 

View the [visual regression test report](https://circleci.com/gh/thinkshout/ucpe/276/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by mariacha** [comment]
Looking good!

**Pull request merged**
